version: "3.9"
services:
  design-patterns-workshop:
    environment:
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - type: volume
        source: vscode-server-extensions
        target: /home/plantuml/.vscode-server/extensions
      - type: volume
        source: vscode-server-insiders-extensions
        target: /home/plantuml/.vscode-server-insiders/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server-extensions:
    name: design-patterns-workshop-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: design-patterns-workshop-vscode-server-insiders-extensions
